version: 0.0
os: windows
files:
  - source: \
    destination: C:\temp\WebApp\CI_Test
  
hooks:
  BeforeInstall:
    #- location: .\StageArtifact.ps1
    - location: .\CreateWebSite.ps1
  AfterInstall:
    - location: .\StageArtifact.ps1